### ISSUE TITLE
[Advanced - Task] Todo 컴포넌트 구현

### ISSUE THREAD

**Issue by inaemin** [inaemin/fe-sprint-my-todo-app#7]
### 만들고자 하는 기능이 무엇인가요?
Todo list를 단순히 나열

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [x] Read하는 기능만 구현
2. [x] data 상태에 따라 다른 icon 적용
3. [x] display: Grid
4. [x] overflow 되면 main 부분만 scroll 구현

### 예상 작업 시간
3h
